version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: startup
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
