import type { Metadata } from "next";
import { Amiko, ABeeZee } from "next/font/google";
import "./globals.css";

const amiko = Amiko({
  variable: "--font-amiko",
  subsets: ["latin"],
  weight: ['400', '700']
});

const aBeeZee = ABeeZee({
  variable: "--font-abeezee",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amiko.variable} ${aBeeZee.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
